readFromFile_rndSeed – RNDGEN module
readFromFile_rndSeed Subroutine
GNU Free Documentation License
6 statements
Source File
private subroutine readFromFile_rndSeed(this, und)
Read the seeds from a file unit
Type Bound
rndSeed
Arguments
Type Intent Optional Attributes Name
class(rndSeed) :: this
integer, intent(in) :: und
Called by
Call graph
read_seed_filename_rndgen calls readfromfile
read_seed_rndgen calls readfromfile
readfromfile_filename_rndseed calls readfromfile