rnd_rndgen_dp – RNDGEN module
rnd_rndgen_dp Function
GNU Free Documentation License
13 statements
Source File
private function rnd_rndgen_dp(this) result(rnd_number)
Generates a random number in the range [0, 1)
Type Bound
rndgen
Arguments
Type Intent Optional Attributes Name
class(rndgen) :: this
Return Value real(kind=dp)
Called by
Call graph
init_rndgen calls rnd_rndgen_dp
int_rndgen_i4 calls rnd_rndgen_dp
int_rndgen_i8 calls rnd_rndgen_dp
real_rndgen_dp calls rnd_rndgen_dp
rnd_array_rnd calls rnd_rndgen_dp
rndpl_rndgenpl calls rnd_rndgen_dp
initpl_rndgenpl calls init_rndgen
reset_rndgen calls init_rndgen
rnd_array_int_i4 calls int_rndgen_i4
rnd_array_int_i8 calls int_rndgen_i8
rndpl_array calls rndpl_rndgenpl