saveToFile_rndSeed – RNDGEN module
saveToFile_rndSeed Subroutine
GNU Free Documentation License
7 statements
Source File
private subroutine saveToFile_rndSeed(this, und)
Save the seeds to a file unit
Type Bound
rndSeed
Arguments
Type Intent Optional Attributes Name
class(rndSeed) :: this
integer, intent(in) :: und
Called by
Call graph
save_seed_filename_rndgen calls savetofile
save_seed_rndgen calls savetofile
savetofile_filename_rndseed calls savetofile