saveToFile_filename_rndSeed – RNDGEN module
saveToFile_filename_rndSeed Subroutine
GNU Free Documentation License
9 statements
Source File
private subroutine saveToFile_filename_rndSeed(this, filename)
Save the seeds to a file name
Type Bound
rndSeed
Arguments
Type Intent Optional Attributes Name
class(rndSeed) :: this
character(len=*), intent(in) :: filename
Calls
Called by
Call graph
savetofile_filename_rndseed calls savetofile
save_seed_filename_rndgen calls savetofile
save_seed_rndgen calls savetofile